"""
Revision creation utilities for plugins.
"""

import logging
import yaml as yaml_lib
from io import StringIO
from typing import Dict, Any, TYPE_CHECKING

if TYPE_CHECKING:
    from plugins.core.api import PluginAPI

logger = logging.getLogger(__name__)


def create_revision_with_hyperparameters(
    api: 'PluginAPI',
    name: str,
    hyperparameters: Dict[str, Any],
    behavior_name: str = None,
    notes: str = ""
) -> str:
    """
    Create a new revision with hyperparameter updates.

    This is the recommended method for plugins that tune hyperparameters.
    Properly merges hyperparameters into the nested ML-Agents config structure.

    Args:
        api: PluginAPI instance
        name: Name for the new revision
        hyperparameters: Dict of hyperparameters to update (e.g., {"learning_rate": 0.001})
        behavior_name: Specific behavior to update, or None to update all behaviors
        notes: Description or notes for the revision

    Returns:
        Created revision ID

    Example:
        api.create_revision_with_hyperparameters(
            name="PBT_Gen1_Best",
            hyperparameters={"learning_rate": 0.001, "batch_size": 128},
            notes="Best performer from generation 1"
        )
    """
    try:
        from utils.file_tools import ensure_workspace_path
        from utils.yaml_tools import (
            load_yaml_with_comments,
            merge_hyperparameters_into_config,
            validate_mlagents_config
        )
        from models import RevisionBody

        # Get experiment ID
        experiment_id = api.context.target_id
        if api.context.scope != 'experiment':
            run = api.db.runs.find_one({"_id": api.context.target_id})
            experiment_id = run["experiment_id"]

        experiment = api.db.experiments.find_one({"_id": experiment_id})
        if not experiment:
            raise ValueError(f"Experiment {experiment_id} not found")

        # Get latest revision
        latest_revision = api.db.revisions.find_one(
            {"experiment_id": experiment_id},
            sort=[("created_at", -1)]
        )
        if not latest_revision:
            raise ValueError(
                f"No parent revision found for experiment {experiment_id}. "
                "Create an initial revision first."
            )

        parent_revision_id = str(latest_revision["_id"])
        environment_id = latest_revision.get("environment_id")

        # Load parent YAML with comment preservation
        parent_yaml_path = ensure_workspace_path(latest_revision["yaml_path"])
        base_config, yaml_handler = load_yaml_with_comments(parent_yaml_path)

        # Merge hyperparameters into correct nested location
        updated_config = merge_hyperparameters_into_config(
            base_config,
            hyperparameters,
            behavior_name
        )

        # Validate the updated config
        validate_mlagents_config(updated_config)

        # Convert config to YAML string (preserve comments if possible)
        yaml_stream = StringIO()
        yaml_handler.dump(updated_config, yaml_stream)
        yaml_content = yaml_stream.getvalue()

        # Create RevisionBody for service
        revision_body = RevisionBody(
            experiment_id=experiment_id,
            name=name,
            description=notes or f"Auto-generated by {api.context.plugin_name}",
            parent_revision_id=parent_revision_id,
            parent_run_id="",
            yaml=yaml_content,
            cli_flags=hyperparameters,
            environment_id=environment_id
        )

        # Use service to create revision (handles all directory creation and DB operations)
        created_revision = api.revisions_service.create_revision(revision_body)
        revision_id = created_revision["_id"]

        logger.info(f"Plugin {api.context.plugin_name} created revision {revision_id} with hyperparameters")
        return revision_id

    except Exception as e:
        logger.error(f"Error creating revision with hyperparameters in plugin {api.context.plugin_name}: {e}")
        raise


def create_revision_with_config_updates(
    api: 'PluginAPI',
    name: str,
    config_updates: Dict[str, Any],
    merge_strategy: str = "deep",
    notes: str = ""
) -> str:
    """
    Create a new revision with custom configuration updates.

    For advanced use cases requiring updates beyond hyperparameters.

    Args:
        api: PluginAPI instance
        name: Name for the new revision
        config_updates: Dictionary of config updates to merge
        merge_strategy: "deep" (recursive merge) or "shallow" (top-level merge)
        notes: Description or notes for the revision

    Returns:
        Created revision ID

    Example:
        api.create_revision_with_config_updates(
            name="BiggerNetwork",
            config_updates={
                "behaviors": {
                    "EnemyBehavior": {
                        "network_settings": {
                            "hidden_units": 256,
                            "num_layers": 3
                        }
                    }
                }
            }
        )
    """
    try:
        from utils.file_tools import ensure_workspace_path
        from utils.yaml_tools import (
            load_yaml_with_comments,
            deep_merge_dict,
            validate_mlagents_config
        )
        from models import RevisionBody

        # Get experiment ID
        experiment_id = api.context.target_id
        if api.context.scope != 'experiment':
            run = api.db.runs.find_one({"_id": api.context.target_id})
            experiment_id = run["experiment_id"]

        experiment = api.db.experiments.find_one({"_id": experiment_id})
        if not experiment:
            raise ValueError(f"Experiment {experiment_id} not found")

        # Get latest revision
        latest_revision = api.db.revisions.find_one(
            {"experiment_id": experiment_id},
            sort=[("created_at", -1)]
        )
        if not latest_revision:
            raise ValueError(
                f"No parent revision found for experiment {experiment_id}. "
                "Create an initial revision first."
            )

        parent_revision_id = str(latest_revision["_id"])
        environment_id = latest_revision.get("environment_id")

        # Load parent YAML with comment preservation
        parent_yaml_path = ensure_workspace_path(latest_revision["yaml_path"])
        base_config, yaml_handler = load_yaml_with_comments(parent_yaml_path)

        # Merge based on strategy
        if merge_strategy == "deep":
            updated_config = deep_merge_dict(base_config, config_updates)
        else:
            # Shallow merge
            updated_config = dict(base_config)
            updated_config.update(config_updates)

        # Validate the updated config
        validate_mlagents_config(updated_config)

        # Convert config to YAML string (preserve comments if possible)
        yaml_stream = StringIO()
        yaml_handler.dump(updated_config, yaml_stream)
        yaml_content = yaml_stream.getvalue()

        # Create RevisionBody for service
        revision_body = RevisionBody(
            experiment_id=experiment_id,
            name=name,
            description=notes or f"Auto-generated by {api.context.plugin_name}",
            parent_revision_id=parent_revision_id,
            parent_run_id="",
            yaml=yaml_content,
            cli_flags=config_updates,
            environment_id=environment_id
        )

        # Use service to create revision (handles all directory creation and DB operations)
        created_revision = api.revisions_service.create_revision(revision_body)
        revision_id = created_revision["_id"]

        logger.info(f"Plugin {api.context.plugin_name} created revision {revision_id} with config updates")
        return revision_id

    except Exception as e:
        logger.error(f"Error creating revision with config updates in plugin {api.context.plugin_name}: {e}")
        raise


def create_revision(
    api: 'PluginAPI',
    name: str,
    config: Dict[str, Any],
    notes: str = "",
    yaml_content: str = None,
    parent_revision_id: str = None,
    parent_run_id: str = None,
    environment_id: str = None
) -> str:
    """
    Create a new experiment revision (low-level method).

    NOTE: For hyperparameter tuning, use create_revision_with_hyperparameters() instead.
    This method uses RevisionsService for proper revision creation.

    Args:
        api: PluginAPI instance
        name: Name for the new revision
        config: Configuration dictionary
        notes: Description or notes for the revision
        yaml_content: Optional pre-formatted YAML content
        parent_revision_id: Optional parent revision ID
        parent_run_id: Optional parent run ID
        environment_id: Optional environment ID

    Returns:
        Created revision ID
    """
    try:
        from utils.file_tools import ensure_workspace_path
        from utils.yaml_tools import (
            load_yaml_with_comments,
            deep_merge_dict,
            validate_mlagents_config
        )
        from models import RevisionBody

        # Get experiment ID
        experiment_id = api.context.target_id
        if api.context.scope != 'experiment':
            run = api.db.runs.find_one({"_id": api.context.target_id})
            experiment_id = run["experiment_id"]

        experiment = api.db.experiments.find_one({"_id": experiment_id})
        if not experiment:
            raise ValueError(f"Experiment {experiment_id} not found")

        # If no parent revision specified, try to get the latest one
        if not parent_revision_id:
            latest_revision = api.db.revisions.find_one(
                {"experiment_id": experiment_id},
                sort=[("created_at", -1)]
            )
            parent_revision_id = str(latest_revision["_id"]) if latest_revision else None

        # Get environment_id from parent revision if not provided
        if not environment_id:
            if parent_revision_id:
                parent_rev = api.db.revisions.find_one({"_id": parent_revision_id})
                environment_id = parent_rev.get("environment_id") if parent_rev else None

            if not environment_id:
                raise ValueError(
                    f"Cannot create revision: no environment_id provided and no parent revision found. "
                    "Please create an initial revision for the experiment first."
                )

        # Prepare YAML content
        if not yaml_content:
            # Load parent revision and merge with new config
            if parent_revision_id:
                parent_rev = api.db.revisions.find_one({"_id": parent_revision_id})
                if parent_rev and parent_rev.get("yaml_path"):
                    parent_yaml_path = ensure_workspace_path(parent_rev["yaml_path"])
                    try:
                        base_config, yaml_handler = load_yaml_with_comments(parent_yaml_path)
                    except Exception as e:
                        logger.warning(f"Could not load parent YAML with comments: {e}, using basic load")
                        with open(parent_yaml_path, 'r') as f:
                            base_config = yaml_lib.safe_load(f) or {}
                        yaml_handler = None
                else:
                    base_config = {}
                    yaml_handler = None
            else:
                base_config = {}
                yaml_handler = None

            # Deep merge configs
            updated_config = deep_merge_dict(base_config, config)

            # Validate config
            try:
                validate_mlagents_config(updated_config)
            except Exception as e:
                logger.warning(f"Config validation warning: {e}")

            # Convert to YAML string
            if yaml_handler:
                yaml_stream = StringIO()
                yaml_handler.dump(updated_config, yaml_stream)
                yaml_content = yaml_stream.getvalue()
            else:
                yaml_content = yaml_lib.dump(updated_config, default_flow_style=False)

        # Create RevisionBody for service
        revision_body = RevisionBody(
            experiment_id=experiment_id,
            name=name,
            description=notes or f"Auto-generated by {api.context.plugin_name}",
            parent_revision_id=parent_revision_id or "",
            parent_run_id=parent_run_id or "",
            yaml=yaml_content,
            cli_flags=config,
            environment_id=environment_id
        )

        # Use service to create revision (handles all directory creation and DB operations)
        created_revision = api.revisions_service.create_revision(revision_body)
        revision_id = created_revision["_id"]

        logger.info(f"Plugin {api.context.plugin_name} created revision {revision_id}")
        return revision_id

    except Exception as e:
        logger.error(f"Error creating revision in plugin {api.context.plugin_name}: {e}")
        raise
